### ISSUE TITLE
step sensor database methods

### ISSUE THREAD

**Issue by SimoravaIT** [SimoravaIT/Tamagotchi_Android#33]
creation of methods responsabile to manage the table of the step sensor :
-loadstep
-loaSingleStep
-loadStepByDay

**Comment by edogab33** [comment]
There is already an issue regarding the step counter [here](https://github.com/SimoravaIT/Tamagotchi_Android/issues/19), so please do not open an issue for every method implemented but connect everything to the one linked before. This helps us to better understand the state of the development of the entire application, since it is logically divided in use cases and roughly each issue should correspond to one use case (unless it is a bug, something not predicted before, or not regarding them), hence the technical details are already encapsulated in the issue #19.

If it can be helpful for you, comments can be left in the thread of the issue in order to keep track of the implementation and to keep updated the entire team.
